### ISSUE TITLE
what happens

### ISSUE THREAD

**Issue by ghost** [sadicann/andor#2]
url like: https://www.site.com/en/fines/test34/service=4334

go run andor.go --url "https://www.site.com/en/fines/test34/service=4334"

it asks me parameter for boolean-based, and I give service
![image](https://user-images.githubusercontent.com/29623610/70497991-6aa70e00-1b2e-11ea-80e5-ce5e821837b4.png)

then asks 
![image](https://user-images.githubusercontent.com/29623610/70498004-772b6680-1b2e-11ea-8f79-1d65350852e4.png)
but I can not type pwn command and it stops
![image](https://user-images.githubusercontent.com/29623610/70498026-890d0980-1b2e-11ea-8163-8d99d9aa9a54.png)

**Comment by sadicann** [comment]
Can you share real url with me ?

**Comment by ghost** [comment]
ok, I sent you url via your email (sadican@hotmail.com.tr)

**Comment by ghost** [comment]
any updates ? :)

**Comment by sadicann** [comment]
Still i'm working on this issue. Sorry. But i will solve this.

**Comment by sadicann** [comment]
Issue fixed
