### ISSUE TITLE
When I try to run it

### ISSUE THREAD

**Issue by braindamagedjustnow** [sadicann/andor#4]
go run andor.go 

andor.go:6:2: cannot find package "github.com/alexflint/go-arg" in any of:
	/usr/local/go/src/github.com/alexflint/go-arg (from $GOROOT)
	/root/go/src/github.com/alexflint/go-arg (from $GOPATH)
andor.go:7:2: cannot find package "github.com/common-nighthawk/go-figure" in any of:
	/usr/local/go/src/github.com/common-nighthawk/go-figure (from $GOROOT)
	/root/go/src/github.com/common-nighthawk/go-figure (from $GOPATH)
andor.go:8:2: cannot find package "github.com/fatih/color" in any of:
	/usr/local/go/src/github.com/fatih/color (from $GOROOT)
	/root/go/src/github.com/fatih/color (from $GOPATH)
andor.go:9:2: cannot find package "github.com/inancgumus/screen" in any of:
	/usr/local/go/src/github.com/inancgumus/screen (from $GOROOT)
	/root/go/src/github.com/inancgumus/screen (from $GOPATH)
andor.go:10:2: cannot find package "github.com/k3a/html2text" in any of:
	/usr/local/go/src/github.com/k3a/html2text (from $GOROOT)
	/root/go/src/github.com/k3a/html2text (from $GOPATH)

**Comment by sadicann** [comment]
You must need install packages. You can install with "go get".
```
go get github.com/alexflint/go-arg
go get github.com/common-nighthawk/go-figure
go get github.com/fatih/color
go get github.com/inancgumus/screen"
go get github.com/k3a/html2text"
```

**Comment by braindamagedjustnow** [comment]
Yes it's working now. Thank you!
