### ISSUE TITLE
no required module provides package

### ISSUE THREAD

**Issue by hassankhan98** [sadicann/andor#5]
any solution?
![Screen Shot 2021-12-11 at 3 11 58 PM](https://user-images.githubusercontent.com/33081303/145672831-1ed957ab-20f6-4786-9594-d9daffcd2568.png)

**Comment by aravindd007** [comment]
Same error

**Comment by sadicann** [comment]
I solved the problem by creating the go.mod file. 
It was fixed after new commit

**Comment by aravindd007** [comment]
hi can you bit more explain about the tool please.

**Comment by sadicann** [comment]
Andor is Blind SQL Injection attack tool, written in Go. 
If you wonder about Blind SQL Injection, you can start from here: https://owasp.org/www-community/attacks/Blind_SQL_Injection

**Comment by aravindd007** [comment]
I think I got a false positive, when I checked this website using Andor (
https://www.laboshop.com/index.php?id=5&L=1) can you make sure of that
please.

**Comment by aravindd007** [comment]
it's says error based sqli.

**Comment by sadicann** [comment]
Sorry but I can't test this website for security reasons. There may be a high probability of being false-positive. Alternatively, you can try SQLMap

**Comment by aravindd007** [comment]
if you're good in SQLI can you please share some tips.

**Comment by sadicann** [comment]
Sorry, there are many learning materials on the internet.

**Comment by aravindd007** [comment]
Yes but , some time tips and play major role to find Sqli.

**Comment by aravindd007** [comment]
anyway this tool extract db?
